### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by dracebus** [upnxt/upnxt-dash-arp-sniffer#1]
Hi there! I read your entry on the upnxt blog, but I am having a hard time trying to compile and launch your solution.
I am getting multiple compile errors:
            if (packet?.Type == EthernetPacketType.Arp)
                PostDashEvent(packet);

it doesnt recognize ?.Type

Any ideas?

Thanks in advance, great work, hope I can make it work :)

**Comment by upnxt** [comment]
Hi dracebus, this project was built with c# 6.0 using the new null conditional operator. If you can't install c# 6.0 you can change recognize?.Type to if (packet != null && packet.Type == EthernetPacketType.Arp)
